### ISSUE TITLE
Could you add a automatic tools requirement 

### ISSUE THREAD

**Issue by AshtakaOOf** [majikdev/rereskillable#5]
it would be very useful and help me a lot because i do other stuff and i wanted to replace project mmo 
but the thing is it doens't automatically add req to tools and weapon 

in the config file of project mmo there is an option that i love called "autoGenerateToolReq" 

and the mods is incredible so keep it alive and if it's too difficult you can try to make an option that import the req created by pmmo

**Comment by AshtakaOOf** [comment]
or is any potential mods that can give me the id of every item and block so i can easily add it to the config file

**Comment by majikdev** [comment]
I won't be adding that because I don't know how. I have been doing it the same way as with Reskillable in 1.12.2 - adding every single item manually. 
What makes it a little bit easier is using Visual Studio Code and the Even Better TOML extension, then right click on the text in the configuration file and press format document, it should format the list of locks vertically instead of as a big wall of text.

**Comment by AshtakaOOf** [comment]
thank
